Tittle: Shathani Sephela
Logo: https://github.com/shatie1738/shatie1738.github.io/blob/main/assets/images/Profile.jpg
show_downloads: True
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
